/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.ggarber.sdpparser

object SdpParser {
    fun parse(string: String): SdpSession {
        val session = SdpSession()
        session.parse(string)
        return session
    }
}
